import {supabase} from '../lib/supabase.js'
export async function profile(id){const r=await supabase.from('profiles').select('*').eq('id',id).single();if(r.error)throw r.error;return r.data}
export async function posts({userId=null,search='',limit=20,offset=0}={}){let q=supabase.from('posts').select('*,profiles!posts_user_id_fkey(id,username,full_name,avatar_url)').order('created_at',{ascending:false}).range(offset,offset+limit-1);if(userId)q=q.eq('user_id',userId);if(search)q=q.ilike('content',`%${search}%`);const r=await q;if(r.error)throw r.error;const list=r.data||[];if(!list.length)return[];const ids=list.map(x=>x.id);const [ls,cs]=await Promise.all([supabase.from('likes').select('post_id,user_id').in('post_id',ids),supabase.from('comments').select('post_id').in('post_id',ids)]);const lc={};const cc={};(ls.data||[]).forEach(x=>{lc[x.post_id]=(lc[x.post_id]||0)+1});(cs.data||[]).forEach(x=>{cc[x.post_id]=(cc[x.post_id]||0)+1});const me=(await supabase.auth.getUser()).data.user;const myLikes=new Set((ls.data||[]).filter(x=>x.user_id===me?.id).map(x=>x.post_id));return list.map(p=>({...p,like_count:lc[p.id]||0,comment_count:cc[p.id]||0,liked:myLikes.has(p.id)}))}
export async function createPost({userId,content,imageUrls=[]}){const payload={user_id:userId,content:content||'',image_url:imageUrls[0]||null,media_urls:imageUrls};const r=await supabase.from('posts').insert(payload).select().single();if(r.error)throw r.error;return r.data}
export async function uploadImages(userId,files,onProgress){const urls=[];for(let i=0;i<files.length;i++){const f=files[i];if(f.size>10*1024*1024)throw Error('Фото больше 10 МБ');const ext=(f.name.split('.').pop()||'jpg').toLowerCase();const path=`${userId}/${crypto.randomUUID()}.${ext}`;const r=await supabase.storage.from('post-images').upload(path,f,{upsert:false});if(r.error)throw r.error;urls.push(supabase.storage.from('post-images').getPublicUrl(path).data.publicUrl);onProgress?.((i+1)/files.length)}return urls}
export async function toggleLike(postId,userId,liked){const r=liked?await supabase.from('likes').delete().eq('post_id',postId).eq('user_id',userId):await supabase.from('likes').insert({post_id:postId,user_id:userId});if(r.error)throw r.error}
export async function comments(postId){const r=await supabase.from('comments').select('*,profiles!comments_user_id_fkey(id,username,full_name,avatar_url)').eq('post_id',postId).order('created_at',{ascending:true}).limit(100);if(r.error)throw r.error;return r.data||[]}
export async function addComment(postId,userId,content,parentId=null){const r=await supabase.from('comments').insert({post_id:postId,user_id:userId,content,parent_id:parentId}).select('*,profiles!comments_user_id_fkey(id,username,full_name,avatar_url)').single();if(r.error)throw r.error;return r.data}
export async function updateComment(id,userId,content){const r=await supabase.from('comments').update({content,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',userId);if(r.error)throw r.error}
export async function deleteComment(id,userId){const r=await supabase.from('comments').delete().eq('id',id).eq('user_id',userId);if(r.error)throw r.error}
export async function deletePost(id,userId){const r=await supabase.from('posts').delete().eq('id',id).eq('user_id',userId);if(r.error)throw r.error}
export async function follow(target,userId,isFollowing){const r=isFollowing?await supabase.from('follows').delete().eq('follower_id',userId).eq('following_id',target):await supabase.from('follows').insert({follower_id:userId,following_id:target});if(r.error)throw r.error}
export async function following(target,userId){return Boolean((await supabase.from('follows').select('follower_id').eq('follower_id',userId).eq('following_id',target).maybeSingle()).data)}
export async function save(postId,userId,saved){const r=saved?await supabase.from('bookmarks').delete().eq('post_id',postId).eq('user_id',userId):await supabase.from('bookmarks').insert({post_id:postId,user_id:userId});if(r.error)throw r.error}
export async function notifications(userId){const r=await supabase.from('notifications').select('*,profiles!notifications_actor_id_fkey(id,username,full_name,avatar_url)').eq('user_id',userId).order('created_at',{ascending:false}).limit(50);if(r.error)throw r.error;return r.data||[]}
export async function markNotifications(userId){await supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',userId).is('read_at',null)}
export async function people(q=''){let s=supabase.from('profiles').select('*').limit(20);if(q)s=s.or(`username.ilike.%${q}%,full_name.ilike.%${q}%`);const r=await s;if(r.error)throw r.error;return r.data||[]}
export async function updateProfile(id,payload){const r=await supabase.from('profiles').update(payload).eq('id',id).select().single();if(r.error)throw r.error;return r.data}
export async function conversations(userId){const r=await supabase.from('conversations').select('id,updated_at,conversation_members!inner(user_id),messages(id,body,created_at,user_id)').eq('conversation_members.user_id',userId).order('updated_at',{ascending:false});if(r.error)throw r.error;return r.data||[]}
export async function startConversation(userId,otherId){const {data:existing}=await supabase.from('conversation_members').select('conversation_id').eq('user_id',userId);const ids=(existing||[]).map(x=>x.conversation_id);if(ids.length){const r=await supabase.from('conversation_members').select('conversation_id').in('conversation_id',ids).eq('user_id',otherId).maybeSingle();if(r.data)return r.data.conversation_id}const c=await supabase.from('conversations').insert({}).select().single();if(c.error)throw c.error;await supabase.from('conversation_members').insert([{conversation_id:c.data.id,user_id:userId},{conversation_id:c.data.id,user_id:otherId}]);return c.data.id}
export async function messageList(conversationId){const r=await supabase.from('messages').select('*,profiles!messages_user_id_fkey(id,username,full_name,avatar_url)').eq('conversation_id',conversationId).order('created_at',{ascending:true}).limit(200);if(r.error)throw r.error;return r.data||[]}
export async function sendMessage(conversationId,userId,body){const r=await supabase.from('messages').insert({conversation_id:conversationId,user_id:userId,body}).select('*,profiles!messages_user_id_fkey(id,username,full_name,avatar_url)').single();if(r.error)throw r.error;return r.data}
