import {conversations,conversationPeople,messageList,sendMessage,people,startConversation} from '../services/data.js'
import {avatar,esc,ago,icon,toast} from '../lib/ui.js'
import {supabase} from '../lib/supabase.js'

let activeId=null,channel=null
export async function renderMessages({app,user}){
 app.innerHTML=`<section class="messages-page"><div class="messages-top"><div><span class="eyebrow">ЛИЧНОЕ</span><h1>Сообщения</h1></div><button class="icon-btn large" id="new-chat">${icon('plus')}</button></div><div class="messages-layout-v2"><aside class="conversation-pane"><div class="chat-search"><span>${icon('search')}</span><input id="chat-search" placeholder="Поиск людей…"></div><div id="people-results"></div><div id="conversation-list" class="conversation-list-v2"><div class="chat-loading">Загружаем диалоги…</div></div></aside><section class="chat-panel-v2" id="chat-panel"><div class="chat-empty"><div class="empty-icon">${icon('chat')}</div><h2>Выбери диалог</h2><p>Начни личный разговор с человеком из города.</p></div></section></div></section>`
 await loadConversations(user)
 const input=document.querySelector('#chat-search');let timer;input.oninput=()=>{clearTimeout(timer);const q=input.value.trim();timer=setTimeout(()=>searchPeople(q,user),250)}
 document.querySelector('#new-chat').onclick=()=>{input.focus();toast('Найди человека по имени или username')}
}
async function loadConversations(user){try{const cs=await conversations(user.id),ids=cs.map(c=>c.id),members=await conversationPeople(ids);const by=new Map();members.forEach(m=>{if(m.user_id!==user.id)by.set(m.conversation_id,m.profiles)});const el=document.querySelector('#conversation-list');el.innerHTML=cs.length?cs.map(c=>{const p=by.get(c.id),last=(c.messages||[]).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0];return `<button class="conversation-row ${activeId===c.id?'active':''}" data-conversation="${c.id}">${avatar(p,'md')}<span><b>${esc(p?.full_name||p?.username||'Диалог')}</b><small>${esc(last?.body||'Начать разговор')}</small></span><time>${last?ago(last.created_at):''}</time></button>`}).join(''):`<div class="empty-state compact"><div class="empty-icon">${icon('chat')}</div><h3>Пока нет диалогов</h3><p>Найди человека и напиши первым.</p></div>`;el.querySelectorAll('[data-conversation]').forEach(b=>b.onclick=()=>openChat(b.dataset.conversation,user,by.get(b.dataset.conversation))) }catch(e){document.querySelector('#conversation-list').innerHTML=`<div class="empty-state compact"><p>${esc(e.message)}</p></div>`}}
async function searchPeople(q,user){const box=document.querySelector('#people-results');if(!q){box.innerHTML='';return}try{const ps=(await people(q)).filter(p=>p.id!==user.id).slice(0,8);box.innerHTML=`<div class="search-title">Люди</div>${ps.map(p=>`<button class="search-person" data-person="${p.id}">${avatar(p,'sm')}<span><b>${esc(p.full_name)}</b><small>@${esc(p.username)}</small></span>${icon('arrow')}</button>`).join('')||'<div class="search-empty">Никого не нашли</div>'}`;box.querySelectorAll('[data-person]').forEach(b=>b.onclick=async()=>{try{const id=await startConversation(user.id,b.dataset.person);document.querySelector('#people-results').innerHTML='';document.querySelector('#chat-search').value='';await loadConversations(user);openChat(id,user,(await people('')).find(p=>p.id===b.dataset.person))}catch(e){toast(e.message,'error')}})}catch(e){box.innerHTML=`<div class="search-empty">${esc(e.message)}</div>`}}
async function openChat(id,user,person){activeId=id;const panel=document.querySelector('#chat-panel');panel.innerHTML=`<header class="chat-head-v2"><div class="chat-person">${avatar(person,'sm')}<div><b>${esc(person?.full_name||person?.username||'Диалог')}</b><small><span class="presence-dot ${person?.last_seen&&Date.now()-new Date(person.last_seen).getTime()<300000?'on':''}"></span>${person?.last_seen&&Date.now()-new Date(person.last_seen).getTime()<300000?'в сети':'был(а) недавно'}</small></div></div><button class="icon-btn">${icon('dots')}</button></header><div class="messages-v2" id="messages"></div><form class="message-form-v2" id="message-form"><textarea id="message-input" rows="1" maxlength="2000" placeholder="Написать сообщение…"></textarea><button class="send-circle" aria-label="Отправить">${icon('send')}</button></form>`;const list=document.querySelector('#messages');try{const ms=await messageList(id);list.innerHTML=ms.length?ms.map(m=>bubble(m,user)).join(''):`<div class="chat-start"><div class="chat-start-avatar">${avatar(person,'lg')}</div><b>Начните разговор</b><span>Напишите ${esc(person?.full_name||'этому человеку')} первое сообщение.</span></div>`;scrollBottom();const form=document.querySelector('#message-form'),input=document.querySelector('#message-input');let typingTimer;input.oninput=()=>{channel?.send({type:'broadcast',event:'typing',payload:{user_id:user.id,typing:true}});clearTimeout(typingTimer);typingTimer=setTimeout(()=>channel?.send({type:'broadcast',event:'typing',payload:{user_id:user.id,typing:false}}),900)};form.onsubmit=async e=>{e.preventDefault();const body=input.value.trim();if(!body)return;input.value='';try{await sendMessage(id,user.id,body);await refreshMessages(id,user)}catch(err){toast(err.message||'Не удалось отправить','error')}};input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}};if(channel)await supabase.removeChannel(channel);channel=supabase.channel(`messages:${id}`,{config:{presence:{key:user.id},broadcast:{self:false}}}).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${id}`},async payload=>{if(payload.new.user_id!==user.id){await refreshMessages(id,user)}}).on('broadcast',{event:'typing'},({payload})=>{if(payload?.user_id!==user.id){const head=document.querySelector('.chat-head-v2 small');if(head)head.innerHTML=payload?.typing?'<span class="presence-dot on"></span>печатает…':'<span class="presence-dot"></span>в сети'}}).subscribe(async status=>{if(status==='SUBSCRIBED')await channel.track({user_id:user.id})})}catch(e){list.innerHTML=`<div class="empty-state compact"><p>${esc(e.message)}</p></div>`}}
async function refreshMessages(id,user){const ms=await messageList(id),el=document.querySelector('#messages');if(!el)return;el.innerHTML=ms.map(m=>bubble(m,user)).join('');scrollBottom()}
function bubble(m,user){return`<div class="bubble-row ${m.user_id===user.id?'mine':''}"><div class="bubble"><span>${esc(m.body)}</span><small>${new Date(m.created_at).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}${m.user_id===user.id?' · ✓':''}</small></div></div>`}
function scrollBottom(){const el=document.querySelector('#messages');if(el)requestAnimationFrame(()=>el.scrollTop=el.scrollHeight)}
