import './style.css'
import {configured,supabase} from './lib/supabase.js'
import {ensureProfile,signOut} from './services/auth.js'
import {authScreen} from './features/auth.js'
import {renderFeed} from './features/feed.js'
import {renderProfile} from './features/profile.js'
import {renderMessages} from './features/messages.js'
import {notifications,markNotifications,people} from './services/data.js'
import {avatar,esc,icon,ago,toast} from './lib/ui.js'

const app=document.querySelector('#app');let user=null,profile=null
if(!configured){app.innerHTML='<main class="auth"><section class="auth-panel"><div class="logo">Т</div><h1>ТВЕРЬ Social</h1><p>Добавь VITE_SUPABASE_URL и VITE_SUPABASE_ANON_KEY в Vercel.</p></section></main>';throw new Error('Supabase env missing')}
const route=()=>{const h=location.hash.replace('#','');if(h.startsWith('profile/'))return['profile',h.split('/')[1]];return[h||'feed',null]}
async function boot(){const s=(await supabase.auth.getSession()).data.session;if(!s){authScreen({onSuccess:()=>boot()});return}user=s.user;profile=await ensureProfile(user);await renderShell();await navigate(route()[0],route()[1])}
async function renderShell(){app.innerHTML=`<div class="app"><header class="topbar"><button class="brand" data-go="feed"><span class="logo mini">Т</span><strong>ТВЕРЬ</strong><em>social</em></button><div class="global-search"><span>${icon('search')}</span><input id="search" placeholder="Поиск людей и публикаций" autocomplete="off"><div id="search-pop"></div></div><div class="top-actions"><button class="icon-btn" data-go="notifications" aria-label="Уведомления">${icon('bell')}<i id="notif-dot"></i></button>${avatar(profile,'sm')}<button class="icon-btn" id="logout" aria-label="Выйти">↪</button></div></header><div class="body"><aside class="sidebar"><nav>${navButton('feed','Главная', 'home')}${navButton('search','Поиск','search')}${navButton('messages','Сообщения','chat')}${navButton('notifications','Уведомления','bell')}${navButton('bookmarks','Закладки','bookmark')}${navButton('profile','Профиль','user')}</nav><div class="sidebar-user">${avatar(profile,'sm')}<div><b>${esc(profile.full_name||profile.username)}</b><small>@${esc(profile.username)}</small></div><button id="logout2">•••</button></div></aside><main id="main"></main></div><nav class="mobile-nav">${navButton('feed','', 'home')}${navButton('search','', 'search')}<button class="create-fab" id="mobile-create">＋</button>${navButton('notifications','', 'bell')}${navButton('profile','', 'user')}</nav></div>`;document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>navigate(x.dataset.go));document.querySelector('#logout').onclick=doLogout;document.querySelector('#logout2').onclick=doLogout;document.querySelector('#mobile-create').onclick=()=>navigate('create');const input=document.querySelector('#search');let timer;input.oninput=()=>{clearTimeout(timer);const q=input.value.trim();timer=setTimeout(()=>searchPop(q),250)};input.onkeydown=e=>{if(e.key==='Enter'&&input.value.trim())navigate('search',input.value.trim())}}
function navButton(id,label,ic){return `<button class="nav-link" data-go="${id}"><span>${icon(ic)}</span><b>${label}</b></button>`}
async function doLogout(){await signOut();location.hash='';boot()}
async function navigate(view,param){if(view==='create'){const {renderFeed}=await import('./features/feed.js');return renderFeed({app:document.querySelector('#main'),user,profile,navigate:routeNav}).then(()=>document.querySelector('#new-post')?.click())}if(view==='feed')return renderFeed({app:document.querySelector('#main'),user,profile,navigate:routeNav});if(view==='profile')return renderProfile({app:document.querySelector('#main'),user,id:param||user.id,navigate:routeNav});if(view==='messages')return renderMessages({app:document.querySelector('#main'),user});if(view==='notifications')return renderNotifications();if(view==='search')return renderSearch(param||'');if(view==='bookmarks')return renderBookmarks()}
const routeNav=v=>{location.hash=v==='profile'?`profile/${user.id}`:v;navigate(v,v==='profile'?user.id:null)}
async function renderNotifications(){const list=await notifications(user.id);document.querySelector('#main').innerHTML=`<div class="page-head"><div><span class="eyebrow">АКТИВНОСТЬ</span><h1>Уведомления</h1></div><button class="btn secondary" id="read-all">Отметить прочитанными</button></div><div class="notification-list">${list.length?list.map(n=>`<button class="notification ${n.read_at?'':'unread'}">${avatar(n.profiles,'sm')}<span><b>${esc(n.profiles?.full_name||n.profiles?.username)}</b> ${n.type==='like'?'поставил(а) лайк вашей публикации':'подписался(ась) на вас'}<small>${ago(n.created_at)}</small></span></button>`).join(''):'<div class="empty"><div class="empty-icon">♡</div><h3>Здесь пока тихо</h3><p>Новые действия появятся здесь.</p></div>'}</div>`;document.querySelector('#read-all').onclick=async()=>{await markNotifications(user.id);toast('Готово');renderNotifications()};await markNotifications(user.id)}
async function renderSearch(q){const ps=await people(q);document.querySelector('#main').innerHTML=`<div class="page-head"><div><span class="eyebrow">ПОИСК</span><h1>${q?'Результаты поиска':'Найди людей'}</h1><p>${q?`По запросу «${esc(q)}»`:''}</p></div></div><div class="results">${ps.length?ps.map(p=>`<button class="person-result" data-person="${p.id}">${avatar(p,'md')}<span><b>${esc(p.full_name||p.username)}</b><small>@${esc(p.username)}</small></span></button>`).join(''):'<div class="empty"><div class="empty-icon">⌕</div><h3>Ничего не нашли</h3><p>Проверь написание или попробуй другой запрос.</p></div>'}</div>`;document.querySelectorAll('[data-person]').forEach(x=>x.onclick=()=>{location.hash=`profile/${x.dataset.person}`;navigate('profile',x.dataset.person)})}
async function renderBookmarks(){const {supabase}=await import('./lib/supabase.js');const {posts}=await import('./services/data.js');const b=await supabase.from('bookmarks').select('post_id').eq('user_id',user.id).order('created_at',{ascending:false});const ids=(b.data||[]).map(x=>x.post_id);const all=ids.length?await posts({search:''}).then(x=>ids.map(id=>x.find(p=>p.id===id)).filter(Boolean)):[];document.querySelector('#main').innerHTML=`<div class="page-head"><div><span class="eyebrow">СОХРАНЁННОЕ</span><h1>Закладки</h1><p>Публикации, к которым хочется вернуться.</p></div></div><div class="bookmark-list">${all.length?all.map(p=>`<article class="profile-post">${p.image_url?`<img src="${esc(p.image_url)}" loading="lazy">`:''}<div><small>${esc(p.profiles?.full_name||p.profiles?.username||'Пользователь')} · ${ago(p.created_at)}</small><p>${esc(p.content||'')}</p></div></article>`).join(''):`<div class="empty"><div class="empty-icon">◇</div><h3>Пока пусто</h3><p>Сохраняй интересные публикации из ленты.</p></div>`}</div>`}
async function searchPop(q){const pop=document.querySelector('#search-pop');if(!q){pop.innerHTML='';return}const ps=await people(q);pop.innerHTML=ps.slice(0,6).map(p=>`<button data-person="${p.id}">${avatar(p,'xs')}<span>${esc(p.full_name||p.username)}<small>@${esc(p.username)}</small></span></button>`).join('');pop.querySelectorAll('[data-person]').forEach(x=>x.onclick=()=>{location.hash=`profile/${x.dataset.person}`;navigate('profile',x.dataset.person);pop.innerHTML=''})}
supabase.auth.onAuthStateChange((_e,s)=>{if(s?.user&&!user)boot();if(!s?.user&&user){user=null;profile=null;authScreen({onSuccess:boot})}})
window.addEventListener('hashchange',()=>{const [v,p]=route();if(user)navigate(v,p)})
boot()
